Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  {% for nic in vagrant_network_configs %}
  config.vm.network {{ nic.name | quote }} {% if nic.ip is defined %} {{ nic.ip | quote }} {% endif %}
end
