---

- name: Configure localhost for kubernetes lab
  hosts: 127.0.0.1
  connection: local
  ignore_errors: yes
  become: yes
  vars_files: 
    - "{{ playbook_dir }}/../vars/kube_lab_server.yaml"
  tasks:

  - name: disable firewald
    service:
      name: firewalld
      state: stopped
      enabled: no

  - name: Download repo file for Virtualbox
    get_url:
      url: http://download.virtualbox.org/virtualbox/rpm/rhel/virtualbox.repo
      dest: /etc/yum.repos.d/virtualbox.repo
      mode: 0544

  - name: Install EPEL REPO
    yum:
      name: "{{ epel_repo_url }}"
      state: present

  # Add items via config file instead of list
  - name: Install libselinux as prerequisite for SELinux Ansible module and NFS
    yum:
      update_cache: yes
      name: "{{item}}"
      state: latest
    with_items:
      - libselinux-python
      - libsemanage-python
      - nfs-utils
      - VirtualBox-5.2
      - binutils 
      - gcc 
      - make 
      - patch 
      - libgomp 
      - glibc-headers 
      - glibc-devel 
      - kernel-headers 
      - dkms

  - name: Install vagrant
    yum:
      name: "{{ vagrant_url }}"
      state: present

  - name: Disable SELinux at next reboot
    selinux:
      state: disabled

  - name: Set SELinux in permissive mode until the machine is rebooted
    command: setenforce 0
    ignore_errors: true
    changed_when: false

  - name: Create NFS exports
    file:
      path: "{{ item.path }}"
      state: directory
      owner: root
      group: root
      mode: "{{ item.unix_perms }}"
    with_items:
      - "{{ nfs_exports }}"
  
  - name: Create iso directory
    file:
      path: "{{ iso_dir }}"
      state: directory
      owner: root
      group: root
      mode: 0777

  - name: Download Ubuntu 18.04 iso
    get_url:
      url: "{{ ubuntu_iso_url }}"
      dest: "{{ iso_dir }}/{{ ubuntu_iso_url.split('/')[-1] }}"
      mode: 0755

  # Rewrite with idempotency
  - name: Rebuild kernel modules for Virtualbox
    command: /usr/lib/virtualbox/vboxdrv.sh setup
    
  # Rewrite with idempotency
  - name: add user to group
    command: "usermod -a -G vboxusers {{ local_user }}"

  - name: Create virtualbox host only adapter
    command: "vboxmanage hostonlyif create; vboxmanage hostonlyif ipconfig {{ vbox_host_only_net }} --ip {{ vbox_host_only_ip }}"

# Copy vagrant file to location
# CWD to location
# Run Vagrant up
